// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/content.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockContentRepo is a mock of ContentRepo interface.
type MockContentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockContentRepoMockRecorder
}

// MockContentRepoMockRecorder is the mock recorder for MockContentRepo.
type MockContentRepoMockRecorder struct {
	mock *MockContentRepo
}

// NewMockContentRepo creates a new mock instance.
func NewMockContentRepo(ctrl *gomock.Controller) *MockContentRepo {
	mock := &MockContentRepo{ctrl: ctrl}
	mock.recorder = &MockContentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentRepo) EXPECT() *MockContentRepoMockRecorder {
	return m.recorder
}

// GetContextOwned mocks base method.
func (m *MockContentRepo) GetContextOwned(ctx context.Context, userID, meetingID int64) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContextOwned", ctx, userID, meetingID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetContextOwned indicates an expected call of GetContextOwned.
func (mr *MockContentRepoMockRecorder) GetContextOwned(ctx, userID, meetingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContextOwned", reflect.TypeOf((*MockContentRepo)(nil).GetContextOwned), ctx, userID, meetingID)
}

// GetTranscriptionOwned mocks base method.
func (m *MockContentRepo) GetTranscriptionOwned(ctx context.Context, userID, meetingID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTranscriptionOwned", ctx, userID, meetingID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTranscriptionOwned indicates an expected call of GetTranscriptionOwned.
func (mr *MockContentRepoMockRecorder) GetTranscriptionOwned(ctx, userID, meetingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTranscriptionOwned", reflect.TypeOf((*MockContentRepo)(nil).GetTranscriptionOwned), ctx, userID, meetingID)
}

// UpsertSummary mocks base method.
func (m *MockContentRepo) UpsertSummary(ctx context.Context, meetingID int64, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSummary", ctx, meetingID, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertSummary indicates an expected call of UpsertSummary.
func (mr *MockContentRepoMockRecorder) UpsertSummary(ctx, meetingID, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSummary", reflect.TypeOf((*MockContentRepo)(nil).UpsertSummary), ctx, meetingID, content)
}

// UpsertTranscription mocks base method.
func (m *MockContentRepo) UpsertTranscription(ctx context.Context, meetingID int64, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTranscription", ctx, meetingID, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTranscription indicates an expected call of UpsertTranscription.
func (mr *MockContentRepoMockRecorder) UpsertTranscription(ctx, meetingID, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTranscription", reflect.TypeOf((*MockContentRepo)(nil).UpsertTranscription), ctx, meetingID, content)
}
