// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/meeting.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/olegsys/meeting-assistant/internal/models"
)

// MockMeetingRepo is a mock of MeetingRepo interface.
type MockMeetingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMeetingRepoMockRecorder
}

// MockMeetingRepoMockRecorder is the mock recorder for MockMeetingRepo.
type MockMeetingRepoMockRecorder struct {
	mock *MockMeetingRepo
}

// NewMockMeetingRepo creates a new mock instance.
func NewMockMeetingRepo(ctrl *gomock.Controller) *MockMeetingRepo {
	mock := &MockMeetingRepo{ctrl: ctrl}
	mock.recorder = &MockMeetingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeetingRepo) EXPECT() *MockMeetingRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMeetingRepo) Create(ctx context.Context, userID int64, title string) (models.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, title)
	ret0, _ := ret[0].(models.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMeetingRepoMockRecorder) Create(ctx, userID, title interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMeetingRepo)(nil).Create), ctx, userID, title)
}

// Find mocks base method.
func (m *MockMeetingRepo) Find(ctx context.Context, userID int64, keyword string) ([]models.FindResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, userID, keyword)
	ret0, _ := ret[0].([]models.FindResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockMeetingRepoMockRecorder) Find(ctx, userID, keyword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockMeetingRepo)(nil).Find), ctx, userID, keyword)
}

// List mocks base method.
func (m *MockMeetingRepo) List(ctx context.Context, userID int64) ([]models.MeetingListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]models.MeetingListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMeetingRepoMockRecorder) List(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMeetingRepo)(nil).List), ctx, userID)
}
