// Code generated by MockGen. DO NOT EDIT.
// Source: internal/speech/client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSpeechClient is a mock of Client interface.
type MockSpeechClient struct {
	ctrl     *gomock.Controller
	recorder *MockSpeechClientMockRecorder
}

// MockSpeechClientMockRecorder is the mock recorder for MockSpeechClient.
type MockSpeechClientMockRecorder struct {
	mock *MockSpeechClient
}

// NewMockSpeechClient creates a new mock instance.
func NewMockSpeechClient(ctrl *gomock.Controller) *MockSpeechClient {
	mock := &MockSpeechClient{ctrl: ctrl}
	mock.recorder = &MockSpeechClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpeechClient) EXPECT() *MockSpeechClientMockRecorder {
	return m.recorder
}

// Transcribe mocks base method.
func (m *MockSpeechClient) Transcribe(ctx context.Context, fileName string, content []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transcribe", ctx, fileName, content)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transcribe indicates an expected call of Transcribe.
func (mr *MockSpeechClientMockRecorder) Transcribe(ctx, fileName, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transcribe", reflect.TypeOf((*MockSpeechClient)(nil).Transcribe), ctx, fileName, content)
}
