// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/task.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	models "github.com/olegsys/meeting-assistant/internal/models"
)

// MockTaskRepo is a mock of TaskRepo interface.
type MockTaskRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepoMockRecorder
}

// MockTaskRepoMockRecorder is the mock recorder for MockTaskRepo.
type MockTaskRepoMockRecorder struct {
	mock *MockTaskRepo
}

// NewMockTaskRepo creates a new mock instance.
func NewMockTaskRepo(ctrl *gomock.Controller) *MockTaskRepo {
	mock := &MockTaskRepo{ctrl: ctrl}
	mock.recorder = &MockTaskRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepo) EXPECT() *MockTaskRepoMockRecorder {
	return m.recorder
}

// ClaimCreated mocks base method.
func (m *MockTaskRepo) ClaimCreated(ctx context.Context, limit int) ([]models.ProcessingJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimCreated", ctx, limit)
	ret0, _ := ret[0].([]models.ProcessingJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimCreated indicates an expected call of ClaimCreated.
func (mr *MockTaskRepoMockRecorder) ClaimCreated(ctx, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimCreated", reflect.TypeOf((*MockTaskRepo)(nil).ClaimCreated), ctx, limit)
}

// Create mocks base method.
func (m *MockTaskRepo) Create(ctx context.Context, meetingID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, meetingID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaskRepoMockRecorder) Create(ctx, meetingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskRepo)(nil).Create), ctx, meetingID)
}

// GetStatusOwned mocks base method.
func (m *MockTaskRepo) GetStatusOwned(ctx context.Context, userID, meetingID int64) (models.StatusInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusOwned", ctx, userID, meetingID)
	ret0, _ := ret[0].(models.StatusInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatusOwned indicates an expected call of GetStatusOwned.
func (mr *MockTaskRepoMockRecorder) GetStatusOwned(ctx, userID, meetingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusOwned", reflect.TypeOf((*MockTaskRepo)(nil).GetStatusOwned), ctx, userID, meetingID)
}

// RequeueStale mocks base method.
func (m *MockTaskRepo) RequeueStale(ctx context.Context, staleAfter time.Duration, maxAttempts int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequeueStale", ctx, staleAfter, maxAttempts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequeueStale indicates an expected call of RequeueStale.
func (mr *MockTaskRepoMockRecorder) RequeueStale(ctx, staleAfter, maxAttempts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequeueStale", reflect.TypeOf((*MockTaskRepo)(nil).RequeueStale), ctx, staleAfter, maxAttempts)
}

// RetryFailedOwned mocks base method.
func (m *MockTaskRepo) RetryFailedOwned(ctx context.Context, userID, meetingID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryFailedOwned", ctx, userID, meetingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryFailedOwned indicates an expected call of RetryFailedOwned.
func (mr *MockTaskRepoMockRecorder) RetryFailedOwned(ctx, userID, meetingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryFailedOwned", reflect.TypeOf((*MockTaskRepo)(nil).RetryFailedOwned), ctx, userID, meetingID)
}

// SetFailed mocks base method.
func (m *MockTaskRepo) SetFailed(ctx context.Context, taskID int64, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFailed", ctx, taskID, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFailed indicates an expected call of SetFailed.
func (mr *MockTaskRepoMockRecorder) SetFailed(ctx, taskID, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFailed", reflect.TypeOf((*MockTaskRepo)(nil).SetFailed), ctx, taskID, message)
}

// UpdateStatus mocks base method.
func (m *MockTaskRepo) UpdateStatus(ctx context.Context, taskID int64, status models.ProcessingStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, taskID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTaskRepoMockRecorder) UpdateStatus(ctx, taskID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTaskRepo)(nil).UpdateStatus), ctx, taskID, status)
}
